services:
  vlmcsd:
    image: mikolatero/vlmcsd:latest
    container_name: vlmcsd
    ports:
      - 1688:1688
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1688"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s